[2022-07-07 19:24:28,917] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.convert_to_csv scheduled__2021-03-02T06:00:00+00:00 [queued]>
[2022-07-07 19:24:28,929] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.convert_to_csv scheduled__2021-03-02T06:00:00+00:00 [queued]>
[2022-07-07 19:24:28,929] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-07-07 19:24:28,929] {taskinstance.py:1239} INFO - Starting attempt 8 of 8
[2022-07-07 19:24:28,929] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-07-07 19:24:28,943] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): convert_to_csv> on 2021-03-02 06:00:00+00:00
[2022-07-07 19:24:28,949] {standard_task_runner.py:52} INFO - Started process 4999 to run task
[2022-07-07 19:24:28,956] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'convert_to_csv', 'scheduled__2021-03-02T06:00:00+00:00', '--job-id', '212', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmpekj24lli', '--error-file', '/tmp/tmpf5u4saq5']
[2022-07-07 19:24:28,957] {standard_task_runner.py:77} INFO - Job 212: Subtask convert_to_csv
[2022-07-07 19:24:29,030] {logging_mixin.py:109} INFO - Running <TaskInstance: LocalIngestionDag.convert_to_csv scheduled__2021-03-02T06:00:00+00:00 [running]> on host d7995de6702f
[2022-07-07 19:24:29,079] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-07-07 19:24:29,103] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=LocalIngestionDag
AIRFLOW_CTX_TASK_ID=convert_to_csv
AIRFLOW_CTX_EXECUTION_DATE=2021-03-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-03-02T06:00:00+00:00
[2022-07-07 19:24:29,104] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: format_to_csv() missing 1 required positional argument: 'csv_output'
[2022-07-07 19:24:29,118] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=LocalIngestionDag, task_id=convert_to_csv, execution_date=20210302T060000, start_date=20220707T192428, end_date=20220707T192429
[2022-07-07 19:24:29,132] {standard_task_runner.py:92} ERROR - Failed to execute job 212 for task convert_to_csv
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: format_to_csv() missing 1 required positional argument: 'csv_output'
[2022-07-07 19:24:29,169] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-07-07 19:24:29,212] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
